b1_back_down_cam_infra1_optical_frame:
- - -0.9956164485394606
  - 0.09273609362015886
  - -0.012161592730672677
  - 0.05957411599995131
- - 0.09270598074462069
  - 0.9956889535907568
  - 0.0030180840812962786
  - 0.36594129295435573
- - 0.012389048867917037
  - 0.001877401772900019
  - -0.999921490333483
  - -0.16438618425857213
- - 0.0
  - 0.0
  - 0.0
  - 1.0
parent_frame: vicon/B1_BODY/B1_BODY
