b1_d455_cam_color_optical_frame:
- - -0.99329476731256
  - -0.011488232061409587
  - -0.11503706252154097
  - -0.049242275347874315
- - 0.11503127604040117
  - 0.0011653995472952435
  - -0.9933611867676376
  - -0.3788619331259212
- - 0.011546027974968481
  - -0.9999333289614841
  - 0.00016392072131821145
  - 0.13729010556698462
- - 0.0
  - 0.0
  - 0.0
  - 1.0
parent_frame: vicon/B1_BODY/B1_BODY
