b1_front_cam_infra1_optical_frame:
- - -0.9934225207465016
  - -0.021136282894025755
  - -0.11253867254900385
  - -0.03358558783384591
- - 0.11233623734350809
  - 0.01053621912439893
  - -0.993614390931445
  - -0.5761314348449735
- - 0.022187046968247442
  - -0.9997210839189035
  - -0.008092546869955974
  - -0.07064389159344002
- - 0.0
  - 0.0
  - 0.0
  - 1.0
parent_frame: vicon/B1_BODY/B1_BODY
