b1_front_down_cam_infra1_optical_frame:
- - -0.9935318822737328
  - 0.1111177939690942
  - -0.02339304958860457
  - -0.03436816548049633
- - 0.11085010577539377
  - 0.9937591683794699
  - 0.012448667050268442
  - -0.5448014648218996
- - 0.024630325925512956
  - 0.009775025584946358
  - -0.9996488363018365
  - -0.17086956611794177
- - 0.0
  - 0.0
  - 0.0
  - 1.0
parent_frame: vicon/B1_BODY/B1_BODY
