b1_side_right_cam_infra1_optical_frame:
- - 0.09716224783383032
  - 0.3132679029567395
  - -0.944681278830571
  - -0.13550438808764806
- - 0.9952587751579061
  - -0.026374305302590106
  - 0.09361819529871768
  - -0.000274674333334311
- - 0.004412263258304405
  - -0.949298486776889
  - -0.3143452161812652
  - -0.11721165218593593
- - 0.0
  - 0.0
  - 0.0
  - 1.0
parent_frame: vicon/B1_BODY/B1_BODY
