b1_side_left_cam_infra1_optical_frame:
- - -0.10023097710980577
  - -0.3420347022429562
  - 0.9343265027222477
  - 0.13716949005978915
- - -0.9949281645337178
  - 0.04244643940990123
  - -0.09119346028630176
  - 0.029211673778658336
- - -0.008467505251334884
  - -0.9387281620591736
  - -0.34455440660630776
  - -0.11987593834139396
- - 0.0
  - 0.0
  - 0.0
  - 1.0
parent_frame: vicon/B1_BODY/B1_BODY
