%YAML:1.0

cam0:
  T_cam_imu:
    - [0.9995140689001559, 0.022791841009459943, 0.021264008419246274, 0.0314257126859772]
    - [-0.022745574999259107, 0.9997383687128567, -0.0024151482996338483, 0.0637538475835283]
    - [-0.02131349076541324, 0.0019303126056794775, 0.9997709782768436, 0.020722597001810467]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.00408286103917287, -0.0034917205444858256, -2.7174459240652828e-05, 0.002157185968486034]
  distortion_model: radtan
  intrinsics: [389.3104288567758, 389.9297682708756, 323.19849316619195, 237.69039429081658]
  resolution: [640, 480]
  rostopic: /b1/b1_side_right_cam/infra1/image_rect_raw
  timeshift_cam_imu: -0.0019354648818268988
cam1:
  T_cam_imu:
    - [0.999528141092677, 0.02299379690297755, 0.02036615986881974, -0.01881360611891409]
    - [-0.0229165942595878, 0.999729313806087, -0.004016070760329749, 0.06367599606092293]
    - [-0.02045299174593123, 0.003547452719229406, 0.9997845221385685, 0.020661005095996457]
    - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
    - [0.9999995764418865, 0.00020375141282673816, -0.000897553013142681, -0.050233695801414846]
    - [-0.00020518456342967568, 0.9999987038588491, -0.001596928276050272, -3.822831637659469e-05]
    - [0.0008972264733948563, 0.001597111763681499, 0.9999983221079283, -0.00019157513685554516]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.002479689508013853, -0.0021349299564260805, 0.00010479065642136627, 0.0021657059476103365]
  distortion_model: radtan
  intrinsics: [389.7636565173539, 390.216790308427, 323.16071121380475, 238.2426543820832]
  resolution: [640, 480]
  rostopic: /b1/b1_side_right_cam/infra2/image_rect_raw
  timeshift_cam_imu: -0.001933719381087873