cam0:
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [0.006945420830747408, -0.009896147279691011, 0.0020009468173122842, -0.0006327063663595968]
  distortion_model: radtan
  intrinsics: [380.1166648845343, 380.89336897750553, 318.9173359897529, 238.92097779895195]
  resolution: [640, 480]
  rostopic: /b1/b1_front_down_cam/infra1/image_rect_raw
